### PR TITLE
Batches in HBAVSS-lite

### PR DESCRIPTION
**Pull request by tyurek**
allows the use of hbavss-lite with arbitrarily large batches.

### CODE REVIEW

**Comment by nqyy** [comment]
What's the point of this given we already have the batch hbavss?

**Comment by amiller** [comment]
We need this for comparison since we are not sure for what concrete values of batch size and n the batch version is concretely faster

**Comment by nqyy** [comment]
LGTM.

**Comment by Drake-Eidukas** [comment]
Restarted jenkins build-- not sure why it's been hanging on step 19...

**Review by nqyy — APPROVED** [review]

**Comment by Drake-Eidukas** [comment]
https://github.com/initc3/HoneyBadgerMPC/pull/287

**Pull request closed without merging**
