### PR TITLE
Fixes tasks not being canceled in test_binaryagreement

### LINKED ISSUE #211: `Event loop is closed` errors in `test_batch_reconstruction.py`
There are a large number of `Event loop is closed` errors when you run `test_batch_reconstruction.py`. This is most likely because some the tests are not cleaning up by cancelling their running tasks.

### PR DESCRIPTION
**Pull request by Drake-Eidukas**
Errors like the following annoyed me: 
```
Exception ignored in: <coroutine object binaryagreement.<locals>._recv at 0x7ff2314766c8>
Traceback (most recent call last):
  File "/usr/src/HoneyBadgerMPC/honeybadgermpc/broadcast/binaryagreement.py", line 90, in _recv
    (sender, msg) = await receive()
  File "/usr/src/HoneyBadgerMPC/tests/test_binaryagreement.py", line 51, in _recv
    (i, o) = await queues[j].get()
  File "/usr/local/lib/python3.7/asyncio/queues.py", line 161, in get
    getter.cancel()  # Just in case getter is not done yet.
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 688, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```
This fixes that... and I wonder if something along these lines could help with exceptions being eaten up.

Resolves #211

### CODE REVIEW

**Comment by Drake-Eidukas** [comment]
The whitespace changes were from VSCode auto-formatting on save... but I think it's cleaner this way anyways.

**Review by amiller — CHANGES_REQUESTED** [review]
IMO cancel all tasks in the event loop is overkill. We should only cancel tasks relevant to this module. If it's hard to keep track of them all we could look into one of these trio nursery things or something like that

**Comment by Drake-Eidukas** [comment]
(for reference, here's some lists of tasks running at the end of the tests that get cancelled AND the unit test itself)
`test_binaryagreement_dummy_with_redundant_messages`
```
{
<Task pending coro=<test_binaryagreement_dummy_with_redundant_messages() running at /usr/src/HoneyBadgerMPC/tests/test_binaryagreement.py:154> cb=[_run_until_complete_cb() at /usr/local/lib/python3.7/asyncio/base_events.py:158] created at /usr/local/lib/python3.7/site-packages/pytest_asyncio/plugin.py:158>,
<Task pending coro=<binaryagreement() running at /usr/src/HoneyBadgerMPC/honeybadgermpc/broadcast/binaryagreement.py:186> wait_for=<Future cancelled created at /usr/local/lib/python3.7/asyncio/base_events.py:396> created at /usr/local/lib/python3.7/asyncio/tasks.py:325>
}
```
`test_binaryagreement_dummy_with_byz_message_type`
```
{
<Task pending coro=<test_binaryagreement_dummy_with_byz_message_type() running at /usr/src/HoneyBadgerMPC/tests/test_binaryagreement.py:185> cb=[_run_until_complete_cb() at /usr/local/lib/python3.7/asyncio/base_events.py:158] created at /usr/local/lib/python3.7/site-packages/pytest_asyncio/plugin.py:158>, 
<Task pending coro=<binaryagreement() running at /usr/src/HoneyBadgerMPC/honeybadgermpc/broadcast/binaryagreement.py:186> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fca558646d8>()] created at /usr/local/lib/python3.7/asyncio/base_events.py:396> created at /usr/local/lib/python3.7/asyncio/tasks.py:325>, 
<Task pending coro=<binaryagreement.<locals>._recv() running at /usr/src/HoneyBadgerMPC/honeybadgermpc/broadcast/binaryagreement.py:90> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fca55889708>()] created at /usr/local/lib/python3.7/asyncio/base_events.py:396> created at /usr/local/lib/python3.7/asyncio/tasks.py:325>
}
```
I believe the exception is caused when that last task (recv) is left running, but it hangs unless both that and `binaryagreement()` are cancelled.

**Comment by amiller** [comment]
I think the most reliable solution is that the binary_agreement instance must expose a "cancel" method that can be called externally and cancels all it's contained tasks.

**Comment by Drake-Eidukas** [comment]
None of the quick and dirty solutions I had for this seemed to get anywhere, so I'm going to close this for now as it's not a high priority... just annoying.

**Pull request closed without merging**
