### PR TITLE
Change __nonzero__ to __bool__ in field.py

### PR DESCRIPTION
**Pull request by hanyunx**
We need `bool` instead of `nonzero` in python3.

### CODE REVIEW

**Comment by amiller** [comment]
Thank you @hanyunxu! Could you also add a test of using a field in an if statement in  `test_field.py`

**Comment by hanyunx** [comment]
There is a ` AttributeError: type object 'GF' has no attribute 'get'` error in my test function `test_bool()` which I don't know why.

**Comment by smkuls** [comment]
> There is a ` AttributeError: type object 'GF' has no attribute 'get'` error in my test function `test_bool()` which I don't know why.

There's no `get` function anymore. You directly call the constructor. `GF(2)` and not `GF.get(2)`. This was changed by Drake recently.

**Review by smkuls — APPROVED** [review]
LGTM!

**Pull request merged**
