### PR TITLE
HBAVSS: Use const polynomial commitment

### PR DESCRIPTION
**Pull request by nqyy**
Use the new PolyCommitConst.

The light class and the batch class are totally separate classes now because they are totally different and even more different with the new changes in share recovery.

### CODE REVIEW

**Comment by Drake-Eidukas** [comment]
You'll have to rebase before this can be merged btw

**Comment by amiller** [comment]
@tyurek needs to review this together with #251

**Comment by nqyy** [comment]
I will update that one after this is merged I think.

**Review by tyurek — APPROVED** [review]
Tweaked some interfaces. Looks good to me assuming Travis is happy. Approved.

**Comment by chitianhao** [comment]
I think I should squash

**Pull request merged**
