### PR TITLE
Serialization format and socket connections

### PR DESCRIPTION
**Pull request by smkuls**
Pending issues:

- If you want to run two MPC programs in the same python script then it will require the listener port to be changed. This is not a blocker now and can be taken later.

### CODE REVIEW

**Comment by smkuls** [comment]
This closes #59.

**Comment by amiller** [comment]
Are there instructions how to run this? How do you test it? Sylvain probably has ideas of how to integrate such tests in. I also want to get my tmux style script to work.

**Review by amiller — APPROVED** [review]
This looks great! I like seeing the sockets done this way directly with `loop.sock_recv` rather than using a larger package wrapped by asyncio. I'd like to record somewhere in the issues your thoughts on why not to use the asyncio stream server.

I am happy to merge it now, but a great question maybe @sbellem has ideas for is how we can make a test case out of running multiple processes.

**Comment by amiller** [comment]
trying to reopen didn't really want to merge yet

**Comment by amiller** [comment]
process_router is not well named, it's not a router. It just open sockets, routing is done by whatever is the external network. Let's give it a name that is more evocative of the design choices it makes, like that each node creates a a single listener on one port, for receiving one connection from each party and currently no authentication. How about:

sendrecv_from_socket
I also think it would be better if we listen on one different port for each client, because then in principle we could use VPN software to handle authentication without us having to add that to our codebase.

Right now, we don't have that option because we just rely on the sender of each message to identify themselves correctly.

It doesn't make sense to have "runProgramAsProcess" in passive.py, nor for passive.py to have to import IPC. Let's just move that into ipc.py

**Pull request merged**
