### PR TITLE
Add license file to dicemix

### PR DESCRIPTION
**Pull request by lu562**

### CODE REVIEW

**Review by amiller — APPROVED** [review]
Perfect, thanks!

**Comment by Drake-Eidukas** [comment]
You might want to cherry-pick [this](https://github.com/initc3/HoneyBadgerMPC/pull/235) into your branch so that travis stops having pytest-sugar (it sometimes messes with output), and some tests hang if `pytest-xdist` doesn't have `--load=distfile` on travis (that's not in the linked PR but [another](https://github.com/initc3/HoneyBadgerMPC/pull/247/files#diff-87eee4f25e33cff2b0b4d79ab35a4aadL13))

**Comment by amiller** [comment]
@lu562 can you make this a pull request to dev rather than to asyncmix?

**Comment by lu562** [comment]
yeah will do.

**Comment by lu562** [comment]
I saw you changed it just now, what should I do?

**Comment by amiller** [comment]
now it's changing too much.... the easiest way is just to start from
`dev` branch rather than `asyncmix` branch, add the license file, then
make a new PR

On Mon, Apr 22, 2019 at 5:48 PM Donghang Lu <notifications@github.com> wrote:
>
> I saw you changed it just now, what should I do?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Andrew Miller

**Pull request closed without merging**
